export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST';
export const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS';
export const MY_ORDER_FAIL = 'MY_ORDER_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const ALL_ORDER_REQUEST = 'ALL_ORDER_REQUEST';
export const ALL_ORDER_SUCCESS = 'ALL_ORDER_SUCCESS';
export const ALL_ORDER_FAIL = 'ALL_ORDER_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
